s236328_s236374/s236328_s236374/Models/Bruker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Data.Entity.ModelConfiguration.Conventions;


namespace s236328_s236374.Models
{
    public class BrukerContext : DbContext
    {
        public BrukerContext()
        : base("name=Bruker")
        {
            Database.CreateIfNotExists();
        }
        public DbSet<Bruker> Brukere { get; set; }
        public DbSet<Konto> Kontoer { get; set; }
        public DbSet<Betaling> Betalinger { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }
    }

    public class Bruker
    {
        [Key]
        public int UserID { get; set; }

        public String Fornavn { get; set; }

        public String Etternavn { get; set; }

        [Required(ErrorMessage = "Personnummer er påkrevd.")]
        public String Personnummer { get; set; }

        [Required(ErrorMessage = "Passord er påkrevd.")]
        [DataType(DataType.Password)]
        public String Passord { get; set; }
        public virtual List<Konto> konto { get; set; }

    }
    public class Konto
    {
        [Key]
        public int id { get; set; }
        public string kontonr { get; set; }
        public string kontotype { get; set; }
        public string saldo { get; set; }
        public string Personnummer { get; set; }
        public virtual List<Betaling> betaling { get; set; }
        public virtual Bruker bruker { get; set; }


    }
    public class Betaling
    {
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage = "Navn på mottaker er påkrevd")]
        public string navn { get; set; }
        [Required(ErrorMessage = "Kontonummer til mottaker er påkrevd")]
        public string kontonr { get; set; }
        public string personnummer { get; set; }
        [Required(ErrorMessage = "Skriv inn et beløp")]
        public string sum { get; set; }
        [Required(ErrorMessage = "Velg en dato som beløpet skal sendes på")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public string dato { get; set; }
        public virtual Konto konto { get; set; }
    }

}

s236328_s236374/s236328_s236374/Controllers/BetalingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using s236328_s236374.Models;
using System.Data.Entity;

namespace s236328_s236374.Controllers
{
    public class BetalingController : Controller
    {
        public ActionResult ListAlleBetalinger()
        {
            var db = new Models.BrukerContext();
            List<Models.Betaling> listeAvBetalinger = db.Betalinger.ToList();
            return View(listeAvBetalinger);
        }

        public ActionResult OpprettBetaling()
        {
            return View();
        }

        //Her blir en ny betaling lagt til i databasen, vi har med personnummer for å linke til konto.
        [HttpPost]
        public ActionResult OpprettBetaling(FormCollection innListe)
        {
            try
            {
                using (var db = new BrukerContext())
                {
                    var nyBetaling = new Models.Betaling();
                   
                    nyBetaling.navn = innListe["Navn"];
                    nyBetaling.kontonr = innListe["Kontonr"];
                    nyBetaling.personnummer = HttpContext.Session["Personnummer"].ToString();               
                    nyBetaling.sum = innListe["Sum"] + "kr";
                    nyBetaling.dato = innListe["Dato"];

                    db.Betalinger.Add(nyBetaling);
                    db.SaveChanges();
                    return RedirectToAction("ListAlleBetalinger");
                }
            }
            catch (Exception feil)
            {
                return View();
            }
        }

        public ActionResult Slettbetaling()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Slettbetaling(FormCollection slett, int id =0)
        {
            var db = new BrukerContext();
            Betaling betaling = db.Betalinger.Find(id);
            if(betaling == null)
            {
                return HttpNotFound();
            }
            db.Betalinger.Remove(betaling);
            db.SaveChanges();
            return RedirectToAction("ListAlleBetalinger");
        }
        public ActionResult EndreBetaling(int id = 0)
        {
            var db = new BrukerContext();
            Betaling betaling = db.Betalinger.Find(id);
            if(betaling == null)
            {
                return HttpNotFound();
            }
            return View(betaling);
        }
        [HttpPost]
        public ActionResult EndreBetaling(Betaling betaling)
        {
            var db = new BrukerContext();
            if (ModelState.IsValid)
            {
                using (db)
                {
                    var automatisk = new Betaling();
                    automatisk.personnummer = HttpContext.Session["Personnummer"].ToString();
                    db.Entry(betaling).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("ListAlleBetalinger");
                }

            }
            return View(betaling);

        }
    }
}

s236328_s236374/s236328_s236374/Controllers/BrukerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using s236328_s236374.Models;

namespace s236328_s236374.Controllers
{
    public class BrukerController : Controller
    {
        public ActionResult Index()
        {
            using (BrukerContext db = new BrukerContext())
            {
                return View(db.Brukere.ToList());
            }
        }
        public ActionResult Login()
        {
            return View();
        }

        //Sjekker om Personnummer og passord stemmer, hvis den gjør det logger man inn
        [HttpPost]
        public ActionResult Login(Bruker brukerkonto)
        {
            using (BrukerContext db = new BrukerContext())
            {
                var usr = db.Brukere.Single(u => u.Personnummer == brukerkonto.Personnummer && u.Passord == brukerkonto.Passord);
                if (usr != null)
                {
                    Session["UserID"] = usr.UserID.ToString();
                    Session["Personnummer"] = usr.Personnummer.ToString();
                    return RedirectToAction("ListAlleKontoer", "Konto");
                }
                else
                {
                    ModelState.AddModelError("", "Personnummer eller passord er feil");
                }
            }
            return View();
        }
    }
}

s236328_s236374/s236328_s236374/Controllers/ForsideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace s236328_s236374.Controllers
{
    public class ForsideController : Controller
    {
        // GET: Forside
        public ActionResult Forside()
        {
            return View();
        }
    }
}

s236328_s236374/s236328_s236374/Controllers/KontoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace s236328_s236374.Controllers
{
    public class KontoController : Controller
    {
        public ActionResult ListAlleKontoer()
        {
            var db = new Models.BrukerContext();
            List<Models.Konto> listeAvKontoer = db.Kontoer.ToList();
            return View(listeAvKontoer);
        }
    }
}

s236328_s236374/s236328_s236374/Views/Betaling/EndreBetaling.cshtml
@model s236328_s236374.Models.Betaling

@{
    ViewBag.Title = "EndreBetaling";
}
<br /><br /><br />
<h2>Endre Betalingen</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Betaling</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.navn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.navn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kontonr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kontonr, new { htmlAttributes = new { @class = "form-control", maxlength = 11, minlength = 11} })
                @Html.ValidationMessageFor(model => model.kontonr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sum, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                @Html.ValidationMessageFor(model => model.sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dato, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.dato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.personnummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personnummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personnummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbake til betalingsoversikt", "ListAlleBetalinger")
</div>

s236328_s236374/s236328_s236374/Views/Betaling/ListAlleBetalinger.cshtml
@using s236328_s236374.Models;
@model IEnumerable<s236328_s236374.Models.Betaling>

@{
    ViewBag.Title = "ListAlleBetalinger";
}
<br /><br /><br />
<h2>Oversikt Betalinger</h2>

<p>
    @Html.ActionLink("Ny Betaling", "OpprettBetaling")
</p>
<p>
    @Html.ActionLink("Tilbake til kontoutskrift", "ListAlleKontoer", "Konto")
</p>
<table class="table">
    <tr>
        <th>
            Navn
        </th>
        <th>
            Kontonummer
        </th>
        <th>
            Sum
        </th>
        <th>
            Dato
        </th>
        <th></th>
    </tr>
    @using (BrukerContext db = new BrukerContext())
    {
        var betaling = new BrukerDatabase();
        var mineKontoer = betaling.HentBetalinger(HttpContext.Current.Session["Personnummer"].ToString());
        foreach (var item in mineKontoer.ToList())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.navn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.kontonr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dato)
                </td>
                <td>
                    @Html.ActionLink("Endre", "EndreBetaling", new { id = item.id }) | 
                    @Html.ActionLink("Slett", "Slettbetaling", new { id = item.id })
                </td>
            </tr>
        }

    }


</table>

s236328_s236374/s236328_s236374/Views/Betaling/OpprettBetaling.cshtml
@model s236328_s236374.Models.Betaling

@{
    ViewBag.Title = "OpprettBetaling";
}
<br /><br /><br />
<h2>Ny Betaling</h2>
<div>
    @Html.ActionLink("Tilbake til kontoutskrift", "ListAlleKontoer", "Konto")
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.navn,"Navn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.navn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kontonr,"Kontonummer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kontonr, new { htmlAttributes = new { @class = "form-control", maxlength = 11, minlength = 11} })
                @Html.ValidationMessageFor(model => model.kontonr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sum,"Sum NOK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sum, new { htmlAttributes = new { @class = "form-control", @type = "number"} })
                @Html.ValidationMessageFor(model => model.sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dato, "Dato",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dato, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.dato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Betal" class="btn btn-default" />
            </div>
        </div>
    </div>
}

s236328_s236374/s236328_s236374/Views/Betaling/Slettbetaling.cshtml
@model s236328_s236374.Models.Betaling

@{
    ViewBag.Title = "Slettbetaling";
}
<br /><br /><br />
<h2>Slette Betaling</h2>

<h3>Er du sikker på at du vil slette betalingen?</h3>
<div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            <br /><br />
            @Html.ActionLink("Tilbake til Betalinger", "ListAlleBetalinger")
        </div>
    }
</div>

s236328_s236374/s236328_s236374/Views/Bruker/Login.cshtml
@model s236328_s236374.Models.Bruker

@{
    ViewBag.Title = "Login";
}
<br /><br /><br />
<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Personnummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Personnummer, new { htmlAttributes = new { @class = "form-control", maxlength = 11, minlength = 11} })
                @Html.ValidationMessageFor(model => model.Personnummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Passord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Passord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Passord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Personnummer,"Engangspassord",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Personnummer, new { htmlAttributes = new { @class = "form-control", maxlength = 5, minlength = 5 } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

s236328_s236374/s236328_s236374/Views/Forside/Forside.cshtml
@{
    ViewBag.Title = "Forside";
}
<br /><br /><br />
<h2 style="text-align:center; text-decoration:underline">Velkommen til din nettbank</h2>

<br /><br /><br />

<div>
    <p style="text-decoration:underline">Klikk her for å logge inn i din nettbank</p>
    <button onclick="location.href = '/Bruker/Login';" class="btn btn-default">Logg inn</button>
</div>
<br /><br />
<div style="text-align:center">
    <img src="~/Content/Hioa.png" alt="HIOA" style="width:800px; height:500px;">
</div>

s236328_s236374/s236328_s236374/Views/Konto/ListAlleKontoer.cshtml
@using s236328_s236374.Models
@model IEnumerable<s236328_s236374.Models.Konto>

@{
    ViewBag.Title = "ListAlleKontoer";
}
<br /><br /><br />
<h2>Oversikt Kontoer</h2>

<p>
    @Html.ActionLink("Ny Betaling", "OpprettBetaling", "Betaling")
</p>
<p>
    @Html.ActionLink("Betalingsoversikt", "ListAlleBetalinger", "Betaling")
</p>
<table class="table">
    <tr>
        <th>
           Kontonummer
        </th>
        <th>
            Type Konto
        </th>
        <th>
            Disponibel Saldo
        </th>
        <th></th>
    </tr>
    

    @using (BrukerContext db = new BrukerContext())
    {
        if (HttpContext.Current.Session["Personnummer"].ToString() != null)
        {
            var konto = new BrukerDatabase();
            var mineKontoer = konto.HentKonti(HttpContext.Current.Session["Personnummer"].ToString());

            foreach (var item in mineKontoer)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.kontonr)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.kontotype)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.saldo) kr
                    </td>
                </tr>
            }
        }

    }
</table>

s236328_s236374/s236328_s236374/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body background="/Content/background-clean.png">
    <div class="navbar navbar-inverse navbar-fixed-top" style="height: 100px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HIOA Nettbank", "Forside", "Forside", new { area = "" }, new { @class = "navbar-brand", @style = "font-size: 48px; color: #ffffff" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nettbank av Robin og Jonas</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>